FROM node:20

LABEL org.opencontainers.image.source=https://github.com/fedal-nl/aklahlana-website

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm install

COPY . .

EXPOSE 3001

CMD ["npm", "run", "dev", "--", "--host"]